### ISSUE TITLE
Clarification regarding variable map_scale

### ISSUE THREAD

**Issue by shivanshpatel35** [srama2512/mapnet-pytorch#1]
Hi,
I am trying to understand the code for AVD dataset. Can you please elaborate on the intuition behind variable map_scale?

**Comment by srama2512** [comment]
The map-scale, in the context of AVD, is the grid-cell size in mm. The original paper uses a discretization of 300mm as the grid-cell size for AVD (Sec 4.3 in https://www.robots.ox.ac.uk/~vedaldi/assets/pubs/henriques18mapnet.pdf).

**Comment by shivanshpatel35** [comment]
Thanks for the clarification!
